<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRffvoyd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRffvoyd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRffvoyd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRffvoyd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRffvoyd\appProdProjectContainer([
    'container.build_hash' => 'Rffvoyd',
    'container.build_id' => 'ecbb9058',
    'container.build_time' => 1631804070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRffvoyd');
